{
 "title": "b2b-platform",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL - QPS ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  rate(pg_stat_database_xact_commit{datname!~\"template0|template1\"}[1m]) +\r\n  rate(pg_stat_database_xact_rollback{datname!~\"template0|template1\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top endpoints by p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\r\n  histogram_quantile(\r\n    0.95,\r\n    sum by (le, job, endpoint) (rate(http_request_duration_seconds_bucket[5m]))\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top endpoints by RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (job, endpoint, method) (\r\n    rate(http_requests_received_total{endpoint!~\".*health.*|/metrics\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{job}} {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "p99 latency by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL - Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  pg_stat_activity_count{backend_type=\"client backend\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in progress requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by (job) (http_requests_in_progress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\r\n  container_memory_working_set_bytes{container_label_com_docker_compose_service!=\"\"}\r\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "100 * sum by (container_label_com_docker_compose_service) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    cpu=\"total\",\r\n    container_label_com_docker_compose_service=~\"auth\\\\.service|auth\\\\.business|service\\\\..*|postgres|mongo|redis|rabbitmq\"\r\n  }[1m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}